######################################################################
# Automatically generated by qmake (3.1) Thu Jun 8 16:28:03 2017
######################################################################

TEMPLATE = app
TARGET = Simulador-MT
INCLUDEPATH += .

# Input
HEADERS += ui_layout.h
FORMS += layout.ui
SOURCES += main.cpp
QT += widgets
